/**
 * 🔧 _mock/mypageProducts.ts
 * 🔧 마이페이지 루틴 스텝 추천 제품 더미 데이터 — 임시 하드코딩, 실제 데이터 아님
 *
 * ⚠️ API 교체 대상
 *    교체 시: productService.getRecommendedByStep(stepCode) 로 대체
 *
 * 사용처:
 *   - src/app/(main)/mypage/page.tsx → STEP_PRODUCTS
 */
import { LocalProduct } from "@/stores";

/** 🔧 스텝별 추천 제품 목록 — ⚠️ API 연동 시 삭제 */
export const STEP_PRODUCTS: LocalProduct[] = [
  {
    id: "c1",
    brand: "아벤느",
    name: "클린스 포밍 젤",
    category: "폼/젤/밤/오일",
    emoji: "🫧",
    skinTypes: ["건성"],
    effects: ["진정", "수분"],
    matchScore: 78,
    price: 19000,
    ewgSafe: 18,
    ewgCaution: 4,
    ewgDanger: 1,
  },
  {
    id: "c2",
    brand: "세타필",
    name: "젠틀 스킨 클렌저",
    category: "폼/젤/밤/오일",
    emoji: "🧴",
    skinTypes: ["건성"],
    effects: ["수분", "진정"],
    matchScore: 82,
    price: 15000,
    ewgSafe: 12,
    ewgCaution: 3,
    ewgDanger: 0,
  },
  {
    id: "t1",
    brand: "아누아",
    name: "어성초 77 토너",
    category: "스킨/토너",
    emoji: "💧",
    skinTypes: ["지성", "복합성"],
    effects: ["여드름", "피지", "진정"],
    matchScore: 92,
    price: 24000,
    ewgSafe: 18,
    ewgCaution: 4,
    ewgDanger: 1,
  },
  {
    id: "t2",
    brand: "미샤",
    name: "[니어스킨] 트러블컷 프레시 토너",
    category: "스킨/토너",
    emoji: "💦",
    skinTypes: ["지성", "복합성"],
    effects: ["여드름", "피지", "블랙헤드", "진정"],
    matchScore: 88,
    price: 12000,
    ewgSafe: 16,
    ewgCaution: 5,
    ewgDanger: 1,
  },
  {
    id: "t3",
    brand: "피터스",
    name: "0.5% 바하토너",
    category: "스킨/토너",
    emoji: "🌊",
    skinTypes: ["지성", "수부지"],
    effects: ["여드름", "미백", "피지", "블랙헤드"],
    matchScore: 85,
    price: 22000,
    ewgSafe: 15,
    ewgCaution: 6,
    ewgDanger: 2,
  },
  {
    id: "t4",
    brand: "라운드랩",
    name: "1025 독도 토너",
    category: "스킨/토너",
    emoji: "🌿",
    skinTypes: ["건성"],
    effects: ["수분", "진정"],
    matchScore: 87,
    price: 18000,
    ewgSafe: 20,
    ewgCaution: 3,
    ewgDanger: 0,
  },
  {
    id: "s1",
    brand: "코스알엑스",
    name: "달팽이 뮤신 96 에센스",
    category: "에센스/앰플/세럼",
    emoji: "✨",
    skinTypes: ["복합성", "건성"],
    effects: ["수분", "안티에이징", "진정"],
    matchScore: 95,
    price: 28000,
    ewgSafe: 22,
    ewgCaution: 2,
    ewgDanger: 0,
  },
  {
    id: "s2",
    brand: "이니스프리",
    name: "그린티 씨드 세럼",
    category: "에센스/앰플/세럼",
    emoji: "🌱",
    skinTypes: ["건성", "복합성"],
    effects: ["수분", "영양"],
    matchScore: 88,
    price: 32000,
    ewgSafe: 19,
    ewgCaution: 5,
    ewgDanger: 2,
  },
  {
    id: "s3",
    brand: "넘버즈인",
    name: "1번 비타민C 세럼",
    category: "에센스/앰플/세럼",
    emoji: "🍋",
    skinTypes: ["건성"],
    effects: ["미백", "색소침착", "안티에이징"],
    matchScore: 83,
    price: 38000,
    ewgSafe: 15,
    ewgCaution: 6,
    ewgDanger: 2,
  },
  {
    id: "cr1",
    brand: "피지오겔",
    name: "AI 크림",
    category: "크림",
    emoji: "🤍",
    skinTypes: ["건성"],
    effects: ["수분", "진정", "아토피"],
    matchScore: 90,
    price: 32000,
    ewgSafe: 21,
    ewgCaution: 3,
    ewgDanger: 0,
  },
  {
    id: "cr2",
    brand: "이니스프리",
    name: "그린티 씨드 크림",
    category: "크림",
    emoji: "💚",
    skinTypes: ["건성", "복합성"],
    effects: ["수분", "영양"],
    matchScore: 86,
    price: 25000,
    ewgSafe: 18,
    ewgCaution: 4,
    ewgDanger: 1,
  },
  {
    id: "sc1",
    brand: "아누아",
    name: "어성초 선크림 SPF50+",
    category: "선크림/스틱",
    emoji: "☀️",
    skinTypes: ["지성", "복합성"],
    effects: ["피지", "진정"],
    matchScore: 91,
    price: 26000,
    ewgSafe: 16,
    ewgCaution: 7,
    ewgDanger: 2,
  },
  {
    id: "sc2",
    brand: "라로슈포제",
    name: "안티헬리오스 XL SPF50+",
    category: "선크림/스틱",
    emoji: "🌤️",
    skinTypes: ["건성"],
    effects: ["진정"],
    matchScore: 86,
    price: 34000,
    ewgSafe: 18,
    ewgCaution: 8,
    ewgDanger: 3,
  },
];
