CATEGORY_HINTS: dict[str, tuple[str, ...]] = {
    "toner": ("토너", "스킨", "화장수", "토닝", "스킨/토너", "토너패드", "toner", "skin toner"),
    "mist": ("미스트", "mist"),
    "cream": ("크림", "cream", "moisturizer", "moisturiser"),
    "lotion": (
        "로션",
        "에멀전",
        "에멀젼",
        "올인원",
        "all in one",
        "all-in-one",
        "allinone",
        "lotion",
        "emulsion",
    ),
    "serum": (
        "세럼",
        "앰플",
        "에센스",
        "에센스/세럼",
        "에센스/앰플/세럼",
        "serum",
        "ampoule",
        "essence",
    ),
    "sunscreen": (
        "선크림",
        "선케어",
        "선 케어",
        "선스틱",
        "자외선",
        "spf",
        "pa",
        "sunscreen",
        "sun cream",
        "sun care",
        "sun stick",
        "sunblock",
    ),
    "cleanser": (
        "클렌징",
        "클렌징워터",
        "클렌징폼",
        "클렌징오일",
        "클렌징밤",
        "클렌징젤",
        "클렌저",
        "세안",
        "폼클렌저",
        "cleanser",
        "cleansing foam",
        "cleansing oil",
        "cleansing balm",
    ),
}

EXISTING_CATEGORY_MARKERS: tuple[str, ...] = (
    "있는데",
    "있고",
    "있어서",
    "있는데",
)

MISSING_CATEGORY_MARKERS: tuple[str, ...] = (
    "없는데",
    "없고",
    "없어서",
    "없는",
    "부족",
    "모자라",
    "필요",
)
