events {
    worker_connections 1024;
}

http {
    # ==========================================
    # 🚀 PROD (운영 서버) - 사용자 접속용
    # ==========================================
    server {
        listen 80;
        server_name j14e101.p.ssafy.io;

        location / {
            proxy_pass http://prod-frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api {
            proxy_pass http://prod-backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ai {
            proxy_pass http://prod-ai:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # ==========================================
    # 🛠️ DEV (개발 서버) - 테스트용
    # ==========================================
    server {
        listen 80;
        server_name dev.piview.com; # 개발용 서브도메인 연결

        location / {
            proxy_pass http://dev-frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api {
            proxy_pass http://dev-backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ai {
            proxy_pass http://dev-ai:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}